fastlane_version "2.13.0"

default_platform :ios

platform :ios do

  desc "UnitTests"
  lane :test do
    scan(
      scheme: "Fluxer-Example",
      devices: ["iPhone 7"]
    )
    slather(
      proj: "Fluxer.xcodeproj",
      scheme: "Fluxer",
      source_directory: "Sources",
      output_directory: "report",
      coveralls: true
    )
  end

end
